# Configure main menu and social menu
[[main]]
identifier = "home"
name = "Home"
url = "/"
[main.params]
icon = "home"
#newtab = true

[[social]]
identifier = "github"
name = "GitHub"
url = "https://github.com/jaredszajkowski"

[social.params]
# icon = "brand-github"
icon = "github-mark-copy"

[[social]]
identifier = "linkedin"
name = "LinkedIn"
url = "https://www.linkedin.com/in/jaredszajkowski/"

[social.params]
icon = "LinkedIn_icon_circle"

[[social]]
identifier = "email"
name = "Email"
url = "mailto:jared.szajkowski@gmail.com"

[social.params]
icon = "4202011_email_gmail_mail_logo_social_icon"

# Twitter below

#[[social]]
#identifier = "twitter"
#name = "Twitter"
#url = "https://twitter.com"

#[social.params]
#icon = "brand-twitter"
